window.Puzzle3DFixture = {
  "title": "Sokoban Literally in 3D",
  "layerCount": 3,
  "size": { "width": 6, "depth": 7, "height": 2 },
  "camera": { "yawDegrees": 15, "pitchDegrees": 55, "zoom": 1.1 },
  "settings": { "interactiveLook": true, "interactiveZoom": true, "grid": { "visibility": 1, "occupied_cells": true }, "shade": true },
  "directions": {
    "up": { "dx": 0, "dy": 0, "dz": 1 },
    "down": { "dx": 0, "dy": 0, "dz": -1 },
    "left": { "dx": -1, "dy": 0, "dz": 0 },
    "right": { "dx": 1, "dy": 0, "dz": 0 },
    "forward": { "dx": 0, "dy": 1, "dz": 0 },
    "backward": { "dx": 0, "dy": -1, "dz": 0 }
  },
  "directionSets": {
    "horizontal": ["left", "right", "forward", "backward"],
    "vertical": ["up", "down"]
  },
  "controls": {
    "keys": {
      "ArrowLeft": "left",
      "ArrowRight": "right",
      "ArrowUp": "forward",
      "ArrowDown": "backward",
      "KeyA": "left",
      "KeyD": "right",
      "KeyW": "forward",
      "KeyS": "backward",
      "a": "left",
      "d": "right",
      "w": "forward",
      "s": "backward",
      "Left": "left",
      "Right": "right",
      "Up": "forward",
      "Down": "backward"
    }
  },
  "inputs": [{ "id": 0, "name": "left", "direction": "left" }, { "id": 1, "name": "right", "direction": "right" }, { "id": 2, "name": "up", "direction": "up" }, { "id": 3, "name": "down", "direction": "down" }, { "id": 4, "name": "forward", "direction": "forward" }, { "id": 5, "name": "backward", "direction": "backward" }],
  "rules": [{ "id": 1, "application": "once", "guards": [{ "kind": "input_is", "input": 0 }], "pattern": { "cells": [{ "offset": { "dx": 0, "dy": 0, "dz": 0 }, "require": [3], "forbid": [] }, { "offset": { "dx": -1, "dy": 0, "dz": 0 }, "require": [4], "forbid": [] }, { "offset": { "dx": -2, "dy": 0, "dz": 0 }, "require": [], "forbid": [3, 4, 5] }] }, "writes": [{ "kind": "move", "fromOffset": { "dx": 0, "dy": 0, "dz": 0 }, "toOffset": { "dx": -1, "dy": 0, "dz": 0 }, "object": 3 }, { "kind": "move", "fromOffset": { "dx": -1, "dy": 0, "dz": 0 }, "toOffset": { "dx": -2, "dy": 0, "dz": 0 }, "object": 4 }], "effects": [] }, { "id": 2, "application": "once", "guards": [{ "kind": "input_is", "input": 1 }], "pattern": { "cells": [{ "offset": { "dx": 0, "dy": 0, "dz": 0 }, "require": [3], "forbid": [] }, { "offset": { "dx": 1, "dy": 0, "dz": 0 }, "require": [4], "forbid": [] }, { "offset": { "dx": 2, "dy": 0, "dz": 0 }, "require": [], "forbid": [3, 4, 5] }] }, "writes": [{ "kind": "move", "fromOffset": { "dx": 0, "dy": 0, "dz": 0 }, "toOffset": { "dx": 1, "dy": 0, "dz": 0 }, "object": 3 }, { "kind": "move", "fromOffset": { "dx": 1, "dy": 0, "dz": 0 }, "toOffset": { "dx": 2, "dy": 0, "dz": 0 }, "object": 4 }], "effects": [] }, { "id": 3, "application": "once", "guards": [{ "kind": "input_is", "input": 4 }], "pattern": { "cells": [{ "offset": { "dx": 0, "dy": 0, "dz": 0 }, "require": [3], "forbid": [] }, { "offset": { "dx": 0, "dy": 1, "dz": 0 }, "require": [4], "forbid": [] }, { "offset": { "dx": 0, "dy": 2, "dz": 0 }, "require": [], "forbid": [3, 4, 5] }] }, "writes": [{ "kind": "move", "fromOffset": { "dx": 0, "dy": 0, "dz": 0 }, "toOffset": { "dx": 0, "dy": 1, "dz": 0 }, "object": 3 }, { "kind": "move", "fromOffset": { "dx": 0, "dy": 1, "dz": 0 }, "toOffset": { "dx": 0, "dy": 2, "dz": 0 }, "object": 4 }], "effects": [] }, { "id": 4, "application": "once", "guards": [{ "kind": "input_is", "input": 5 }], "pattern": { "cells": [{ "offset": { "dx": 0, "dy": 0, "dz": 0 }, "require": [3], "forbid": [] }, { "offset": { "dx": 0, "dy": -1, "dz": 0 }, "require": [4], "forbid": [] }, { "offset": { "dx": 0, "dy": -2, "dz": 0 }, "require": [], "forbid": [3, 4, 5] }] }, "writes": [{ "kind": "move", "fromOffset": { "dx": 0, "dy": 0, "dz": 0 }, "toOffset": { "dx": 0, "dy": -1, "dz": 0 }, "object": 3 }, { "kind": "move", "fromOffset": { "dx": 0, "dy": -1, "dz": 0 }, "toOffset": { "dx": 0, "dy": -2, "dz": 0 }, "object": 4 }], "effects": [] }, { "id": 5, "application": "once", "guards": [{ "kind": "input_is", "input": 0 }], "pattern": { "cells": [{ "offset": { "dx": 0, "dy": 0, "dz": 0 }, "require": [3], "forbid": [] }, { "offset": { "dx": -1, "dy": 0, "dz": 0 }, "require": [], "forbid": [3, 4, 5] }] }, "writes": [{ "kind": "move", "fromOffset": { "dx": 0, "dy": 0, "dz": 0 }, "toOffset": { "dx": -1, "dy": 0, "dz": 0 }, "object": 3 }], "effects": [] }, { "id": 6, "application": "once", "guards": [{ "kind": "input_is", "input": 1 }], "pattern": { "cells": [{ "offset": { "dx": 0, "dy": 0, "dz": 0 }, "require": [3], "forbid": [] }, { "offset": { "dx": 1, "dy": 0, "dz": 0 }, "require": [], "forbid": [3, 4, 5] }] }, "writes": [{ "kind": "move", "fromOffset": { "dx": 0, "dy": 0, "dz": 0 }, "toOffset": { "dx": 1, "dy": 0, "dz": 0 }, "object": 3 }], "effects": [] }, { "id": 7, "application": "once", "guards": [{ "kind": "input_is", "input": 4 }], "pattern": { "cells": [{ "offset": { "dx": 0, "dy": 0, "dz": 0 }, "require": [3], "forbid": [] }, { "offset": { "dx": 0, "dy": 1, "dz": 0 }, "require": [], "forbid": [3, 4, 5] }] }, "writes": [{ "kind": "move", "fromOffset": { "dx": 0, "dy": 0, "dz": 0 }, "toOffset": { "dx": 0, "dy": 1, "dz": 0 }, "object": 3 }], "effects": [] }, { "id": 8, "application": "once", "guards": [{ "kind": "input_is", "input": 5 }], "pattern": { "cells": [{ "offset": { "dx": 0, "dy": 0, "dz": 0 }, "require": [3], "forbid": [] }, { "offset": { "dx": 0, "dy": -1, "dz": 0 }, "require": [], "forbid": [3, 4, 5] }] }, "writes": [{ "kind": "move", "fromOffset": { "dx": 0, "dy": 0, "dz": 0 }, "toOffset": { "dx": 0, "dy": -1, "dz": 0 }, "object": 3 }], "effects": [] }],
  "lifecycle": {
    "onLevelStart": [],
    "onLevelClear": ["next_level"]
  },
  "winCondition": { "kind": "all", "conditions": [{ "kind": "some_object", "object": 2 }, { "kind": "no_pattern", "pattern": { "cells": [{ "offset": { "dx": 0, "dy": 0, "dz": 0 }, "require": [], "forbid": [4] }, { "offset": { "dx": 0, "dy": 0, "dz": -1 }, "require": [2], "forbid": [] }] } }] },
  "objects": {
    "Floor": { "id": 1, "name": "Floor", "sprite": "Floor", "layer": 0 },
    "Goal": { "id": 2, "name": "Goal", "sprite": "Goal", "layer": 1 },
    "Player": { "id": 3, "name": "Player", "sprite": "Player", "layer": 2 },
    "Box": { "id": 4, "name": "Box", "sprite": "Box", "layer": 2 },
    "Wall": { "id": 5, "name": "Wall", "sprite": "Wall", "layer": 2 }
  },
  "currentScene": "title",
  "scenes": [
    {
      "name": "title",
      "layout": {},
      "puzzles": [],
      "keys": {},
      "components": [{ "kind": "title", "text": "Microban Basic 3D" }, { "kind": "button", "label": "Start", "action": { "kind": "start_levels", "levels": "microban", "scene": "playing" } }, { "kind": "button", "label": "Level Select", "action": { "kind": "goto", "scene": "level_select" } }]
    },
    {
      "name": "level_select",
      "layout": {},
      "puzzles": [{ "slot": "board", "model": "sokoban_literally_in_3d" }],
      "keys": {},
      "components": [{ "kind": "title", "text": "Select Level" }, { "kind": "level_menu", "levels": "microban", "action": { "kind": "start_levels", "levels": "microban", "scene": "playing" } }, { "kind": "button", "label": "Back", "action": { "kind": "goto", "scene": "title" } }]
    },
    {
      "name": "playing",
      "layout": {},
      "puzzles": [{ "slot": "board", "model": "sokoban_literally_in_3d" }],
      "keys": {"q": { "kind": "goto", "scene": "level_select" }, "Escape": { "kind": "goto", "scene": "level_select" }},
      "components": [{ "kind": "box", "children": [{ "kind": "puzzle3", "source": "board", "layout": {"size": { "width": 7, "height": 7 }} }], "layout": {"size": { "width": 8, "height": 8 }} }]
    }
  ],
  "levelIndex": 0,
  "levels": [
    {
      "name": "microban_01",
      "label": "Microban 01",
      "size": { "width": 6, "depth": 7, "height": 2 },
      "cells": [
        { "position": { "x": 0, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 1, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 2, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 3, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 5, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 3, "y": 5, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 3, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 4, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 5, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 3, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 1, "y": 3, "z": 1 }, "objects": [{ "id": 4, "name": "Box", "sprite": "Box" }] },
        { "position": { "x": 2, "y": 3, "z": 1 }, "objects": [{ "id": 3, "name": "Player", "sprite": "Player" }] },
        { "position": { "x": 5, "y": 3, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 2, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 3, "y": 2, "z": 1 }, "objects": [{ "id": 4, "name": "Box", "sprite": "Box" }] },
        { "position": { "x": 5, "y": 2, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 3, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 4, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 5, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 1, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 2, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 3, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }, { "id": 2, "name": "Goal", "sprite": "Goal" }] },
        { "position": { "x": 3, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }, { "id": 2, "name": "Goal", "sprite": "Goal" }] },
        { "position": { "x": 2, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] }
      ]
    },
    {
      "name": "microban_02",
      "label": "Microban 02",
      "size": { "width": 6, "depth": 7, "height": 2 },
      "cells": [
        { "position": { "x": 0, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 1, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 2, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 3, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 4, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 5, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 5, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 5, "y": 5, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 2, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 3, "y": 4, "z": 1 }, "objects": [{ "id": 3, "name": "Player", "sprite": "Player" }] },
        { "position": { "x": 5, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 3, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 2, "y": 3, "z": 1 }, "objects": [{ "id": 4, "name": "Box", "sprite": "Box" }] },
        { "position": { "x": 3, "y": 3, "z": 1 }, "objects": [{ "id": 4, "name": "Box", "sprite": "Box" }] },
        { "position": { "x": 5, "y": 3, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 2, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 3, "y": 2, "z": 1 }, "objects": [{ "id": 4, "name": "Box", "sprite": "Box" }] },
        { "position": { "x": 5, "y": 2, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 5, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 1, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 2, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 3, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 4, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 5, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }, { "id": 2, "name": "Goal", "sprite": "Goal" }] },
        { "position": { "x": 4, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }, { "id": 2, "name": "Goal", "sprite": "Goal" }] },
        { "position": { "x": 3, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }, { "id": 2, "name": "Goal", "sprite": "Goal" }] },
        { "position": { "x": 4, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] }
      ]
    },
    {
      "name": "microban_03",
      "label": "Microban 03",
      "size": { "width": 9, "depth": 6, "height": 2 },
      "cells": [
        { "position": { "x": 2, "y": 5, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 3, "y": 5, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 4, "y": 5, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 5, "y": 5, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 1, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 2, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 5, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 6, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 7, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 8, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 3, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 6, "y": 3, "z": 1 }, "objects": [{ "id": 4, "name": "Box", "sprite": "Box" }] },
        { "position": { "x": 8, "y": 3, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 2, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 2, "y": 2, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 5, "y": 2, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 6, "y": 2, "z": 1 }, "objects": [{ "id": 4, "name": "Box", "sprite": "Box" }] },
        { "position": { "x": 8, "y": 2, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 5, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 6, "y": 1, "z": 1 }, "objects": [{ "id": 3, "name": "Player", "sprite": "Player" }] },
        { "position": { "x": 8, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 1, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 2, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 3, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 4, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 5, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 6, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 7, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 8, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
        { "position": { "x": 0, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 6, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 7, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 8, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 6, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 7, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 8, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 6, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 7, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 8, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 6, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 7, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 8, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }, { "id": 2, "name": "Goal", "sprite": "Goal" }] },
        { "position": { "x": 3, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }, { "id": 2, "name": "Goal", "sprite": "Goal" }] },
        { "position": { "x": 5, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 6, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 7, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 8, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 0, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 1, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 2, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 3, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 4, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 5, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 6, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 7, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
        { "position": { "x": 8, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] }
      ]
    }
  ],
  "cells": [
    { "position": { "x": 0, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 1, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 2, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 3, "y": 6, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 0, "y": 5, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 3, "y": 5, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 0, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 3, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 4, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 5, "y": 4, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 0, "y": 3, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 1, "y": 3, "z": 1 }, "objects": [{ "id": 4, "name": "Box", "sprite": "Box" }] },
    { "position": { "x": 2, "y": 3, "z": 1 }, "objects": [{ "id": 3, "name": "Player", "sprite": "Player" }] },
    { "position": { "x": 5, "y": 3, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 0, "y": 2, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 3, "y": 2, "z": 1 }, "objects": [{ "id": 4, "name": "Box", "sprite": "Box" }] },
    { "position": { "x": 5, "y": 2, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 0, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 3, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 4, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 5, "y": 1, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 0, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 1, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 2, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 3, "y": 0, "z": 1 }, "objects": [{ "id": 5, "name": "Wall", "sprite": "Wall" }] },
    { "position": { "x": 0, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 1, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 2, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 3, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 4, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 5, "y": 6, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 0, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 1, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 2, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }, { "id": 2, "name": "Goal", "sprite": "Goal" }] },
    { "position": { "x": 3, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 4, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 5, "y": 5, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 0, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 1, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 2, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 3, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 4, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 5, "y": 4, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 0, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 1, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }, { "id": 2, "name": "Goal", "sprite": "Goal" }] },
    { "position": { "x": 2, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 3, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 4, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 5, "y": 3, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 0, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 1, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 2, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 3, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 4, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 5, "y": 2, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 0, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 1, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 2, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 3, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 4, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 5, "y": 1, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 0, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 1, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 2, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 3, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 4, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] },
    { "position": { "x": 5, "y": 0, "z": 0 }, "objects": [{ "id": 1, "name": "Floor", "sprite": "Floor" }] }
  ],
  "levelBundles": {
    "default": [0, 1, 2],
    "levels": [0, 1, 2],
    "microban": [0, 1, 2]
  },
  "sprites": {
    "Floor": {
      "palette": {"0": "#90ee90", "1": "#008000"},
      "bitmap": [
        ".....",
        ".....",
        ".....",
        ".....",
        ".....",
        "",
        ".....",
        ".....",
        ".....",
        ".....",
        ".....",
        "",
        ".....",
        ".....",
        ".....",
        ".....",
        ".....",
        "",
        ".....",
        ".....",
        ".....",
        ".....",
        ".....",
        "",
        "11111",
        "01111",
        "11101",
        "11111",
        "10111"
      ]
    },
    "Goal": {
      "palette": {"0": "#00008b"},
      "bitmap": [
        ".....",
        ".....",
        ".....",
        ".....",
        ".....",
        "",
        ".....",
        ".....",
        ".....",
        ".....",
        ".....",
        "",
        ".....",
        ".....",
        ".....",
        ".....",
        ".....",
        "",
        ".....",
        ".....",
        ".....",
        ".....",
        ".....",
        "",
        ".....",
        ".000.",
        ".0.0.",
        ".000.",
        "....."
      ]
    },
    "Player": {
      "palette": {"0": "#000000", "1": "#ffa500", "2": "#ffffff", "3": "#0000ff"},
      "bitmap": [
        ".....",
        ".....",
        ".3.3.",
        ".....",
        ".....",
        "",
        ".....",
        ".....",
        ".333.",
        ".....",
        ".....",
        "",
        ".....",
        ".....",
        "22222",
        ".....",
        ".....",
        "",
        ".....",
        ".....",
        ".111.",
        ".....",
        ".....",
        "",
        ".....",
        ".....",
        ".000.",
        ".....",
        "....."
      ]
    },
    "Box": {
      "palette": {"0": "#ffa500"},
      "bitmap": [
        "00000",
        "0...0",
        "0...0",
        "0...0",
        "00000",
        "",
        "0...0",
        ".....",
        ".....",
        ".....",
        "0...0",
        "",
        "0...0",
        ".....",
        ".....",
        ".....",
        "0...0",
        "",
        "0...0",
        ".....",
        ".....",
        ".....",
        "0...0",
        "",
        "00000",
        "0...0",
        "0...0",
        "0...0",
        "00000"
      ]
    },
    "Wall": {
      "palette": {"0": "#a46322", "1": "#493c2b"},
      "bitmap": [
        ".....",
        ".....",
        ".....",
        ".....",
        ".....",
        "",
        ".....",
        ".....",
        ".....",
        ".....",
        ".....",
        "",
        "00010",
        "11111",
        "01000",
        "11111",
        "00010",
        "",
        "11111",
        "00010",
        "11111",
        "01000",
        "11111",
        "",
        "00010",
        "11111",
        "01000",
        "11111",
        "00010"
      ]
    }
  }
}
