window.Puzzle3DFixture = {
  title: "Puzzle3 Occupied Cell Grid Preview",
  size: { width: 7, depth: 5, height: 3 },
  camera: { yawDegrees: 34, pitchDegrees: 38, zoom: 1.08 },
  settings: {
    interactiveLook: true,
    interactiveZoom: true,
    grid: {
      visible: true,
      occupied_cells: true,
      color: "rgba(31, 36, 40, 0.66)",
    },
  },
  directions: {
    up: { dx: 0, dy: 0, dz: 1 },
    down: { dx: 0, dy: 0, dz: -1 },
    left: { dx: -1, dy: 0, dz: 0 },
    right: { dx: 1, dy: 0, dz: 0 },
    forward: { dx: 0, dy: 1, dz: 0 },
    backward: { dx: 0, dy: -1, dz: 0 },
  },
  directionSets: {
    horizontal: ["left", "right", "forward", "backward"],
    vertical: ["up", "down"],
  },
  controls: { keys: {} },
  inputs: [],
  rules: [],
  lifecycle: {
    onLevelStart: [],
    onLevelClear: [],
  },
  objects: {
    FilledCube: { id: 1, name: "FilledCube", sprite: "filled_cube", layer: 0 },
    OpenSprite: { id: 2, name: "OpenSprite", sprite: "open_sprite", layer: 0 },
  },
  sprites: {
    filled_cube: {
      palette: { f: "#d94132" },
      bitmap: [
        "ffff",
        "ffff",
        "ffff",
        "ffff",
        "",
        "ffff",
        "ffff",
        "ffff",
        "ffff",
        "",
        "ffff",
        "ffff",
        "ffff",
        "ffff",
        "",
        "ffff",
        "ffff",
        "ffff",
        "ffff",
      ],
    },
    open_sprite: {
      palette: { o: "#2f7ebc" },
      bitmap: [
        "o  o",
        "    ",
        "    ",
        "o  o",
        "",
        "    ",
        " oo ",
        " oo ",
        "    ",
        "",
        "    ",
        " oo ",
        " oo ",
        "    ",
        "",
        "o  o",
        "    ",
        "    ",
        "o  o",
      ],
    },
  },
  currentScene: "preview",
  scenes: [
    {
      name: "preview",
      puzzles: [{ slot: "board", model: "grid_preview" }],
      controls: {},
      keys: {},
      rules: [],
      layout: { size: { width: 12, height: 8 }, gap: 0, align: { x: "center", y: "center" } },
      components: [{ kind: "puzzle3", source: "board", layout: { size: { width: 12, height: 8 } } }],
    },
  ],
  levelIndex: 0,
  levels: [
    {
      name: "occupied_cell_sprite_compare",
      label: "Occupied Cell Sprite Compare",
      size: { width: 7, depth: 5, height: 3 },
      cells: [
        {
          position: { x: 1, y: 1, z: 0 },
          objects: [{ id: 1, name: "FilledCube", sprite: "filled_cube", layer: 0 }],
        },
        {
          position: { x: 4, y: 1, z: 0 },
          objects: [{ id: 2, name: "OpenSprite", sprite: "open_sprite", layer: 0 }],
        },
        {
          position: { x: 2, y: 3, z: 0 },
          objects: [{ id: 1, name: "FilledCube", sprite: "filled_cube", layer: 0 }],
        },
        {
          position: { x: 3, y: 3, z: 0 },
          objects: [{ id: 1, name: "FilledCube", sprite: "filled_cube", layer: 0 }],
        },
        {
          position: { x: 5, y: 3, z: 0 },
          objects: [{ id: 2, name: "OpenSprite", sprite: "open_sprite", layer: 0 }],
        },
        {
          position: { x: 5, y: 3, z: 1 },
          objects: [{ id: 2, name: "OpenSprite", sprite: "open_sprite", layer: 0 }],
        },
      ],
    },
  ],
};
