/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmstandalonesession_free: (a: number, b: number) => void;
export const wasmstandalonesession_apply_debug_input_name: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmstandalonesession_audio_feedback_event: (a: number, b: number) => [number, number];
export const wasmstandalonesession_confirm_progress_save_cleared: (a: number) => void;
export const wasmstandalonesession_confirm_progress_save_written: (a: number, b: number) => [number, number];
export const wasmstandalonesession_dispatch: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmstandalonesession_fromExport: (a: number, b: number) => [number, number, number];
export const wasmstandalonesession_new: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasmstandalonesession_presentation_event_consumed: (a: number, b: number) => [number, number, number, number];
export const wasmstandalonesession_presentation_frame: (a: number, b: number) => [number, number];
export const wasmstandalonesession_progress_save: (a: number) => [number, number];
export const wasmstandalonesession_progress_save_request: (a: number) => [number, number];
export const wasmstandalonesession_progress_storage_key: (a: number) => [number, number];
export const wasmstandalonesession_progress_storage_save_version: (a: number) => number;
export const wasmstandalonesession_restore_progress_save: (a: number, b: number, c: number) => [number, number];
export const wasmstandalonesession_set_audio_feedback_wakeup: (a: number, b: any) => void;
export const wasmstandalonesession_set_audio_visible: (a: number, b: number, c: number) => [number, number];
export const wasmstandalonesession_set_current_state: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasmstandalonesession_set_progress_persistence_enabled: (a: number, b: number) => void;
export const wasmstandalonesession_snapshot: (a: number) => [number, number];
export const wasmstandalonesession_unlock_audio: (a: number, b: number) => any;
export const wasmstandalonesession_visual_image_count: (a: number) => number;
export const wasmstandalonesession_audio_tick: (a: number, b: number) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h5b8ed1e5fec17ec2: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h709bd5d4c0b96c84: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h44b7ab73cd046207: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h44b7ab73cd046207_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4681ec085113b112: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
